//
//  MyStyleKit.h
//  ProjectName
//
//  Created by Ishan Weerasooriya on 10/8/15.
//  Copyright (c) 2015 Appmonkeyz. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface MyStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* chatIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* paperPlaneTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* mailTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* deleteBinTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* locationIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* pencilTargets;

// Colors
+ (UIColor*)customGreen;

// Drawing Methods
+ (void)drawFood;
+ (void)drawLocationIcon;
+ (void)drawPencil;

// Generated Images
+ (UIImage*)imageOfChatIcon;
+ (UIImage*)imageOfPaperPlane;
+ (UIImage*)imageOfMail;
+ (UIImage*)imageOfDeleteBin;
+ (UIImage*)imageOfLocationIcon;
+ (UIImage*)imageOfPencil;

@end
