//
//  AmazingStyleKit.h
//  Amazing
//
//  Created by Ishan Weerasooriya on 10/29/15.
//  Copyright (c) 2015 Appmonkeyz. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface AmazingStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* messageRectangleTargets;

// Drawing Methods
+ (void)drawMessageRectangle;
+ (void)drawTimeLabelWithRemainTime: (NSString*)remainTime;
+ (void)drawFogWheelWithAngleRight: (CGFloat)angleRight angleLeft: (CGFloat)angleLeft;

// Generated Images
+ (UIImage*)imageOfMessageRectangle;
+ (UIImage*)imageOfTimeLabelWithRemainTime: (NSString*)remainTime;
+ (UIImage*)imageOfFogWheelWithAngleRight: (CGFloat)angleRight angleLeft: (CGFloat)angleLeft;

@end
