//
//  StopWatchStyleKit.h
//  StopWatch
//
//  Created by Ishan Weerasooriya on 10/9/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StopWatchStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* nextButtonTargets;

// Drawing Methods
+ (void)drawStopWatchWithSeconds: (CGFloat)seconds minuites: (CGFloat)minuites hours: (CGFloat)hours;

// Generated Images
+ (UIImage*)imageOfStopWatchWithSeconds: (CGFloat)seconds minuites: (CGFloat)minuites hours: (CGFloat)hours;
+ (UIImage*)imageOfPullToRefreshWithAngle: (CGFloat)angle;
+ (UIImage*)imageOfNextButton;

@end
